--------------------------------------------------------
--  파일이 생성됨 - 월요일-6월-15-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SHOP_LOG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HR"."SHOP_LOG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Sequence LOGIN_LOG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HR"."LOGIN_LOG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Sequence GAME_LOG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HR"."GAME_LOG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "HR"."USERS" 
   (	"USER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(100) NOT NULL ENABLE, 
	"USER_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"QUESTION" VARCHAR2(100) NOT NULL ENABLE, 
	"ANSWER" VARCHAR2(20) NOT NULL ENABLE, 
	"GOLD" NUMBER NOT NULL ENABLE, 
	"EXPERIENCE" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "USERS_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
--------------------------------------------------------
--  DDL for Table LOGIN_LOG
--------------------------------------------------------

  CREATE TABLE "HR"."LOGIN_LOG" 
   (	"LOG_ID" NUMBER, 
	"USER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(20) NOT NULL ENABLE, 
	"LOG_DATE" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "LOGIN_LOG_USER_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "HR"."USERS" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
--------------------------------------------------------
--  DDL for Table LAND
--------------------------------------------------------

  CREATE TABLE "HR"."LAND" 
   (	"LAND_ID" NUMBER(10,0), 
	"LAND_TYPE" VARCHAR2(20), 
	"LAND_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"BUY_PRICE" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"TOLL_PRICE" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"UPGRADE_COST" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"UPGRADE_MAX" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE, 
	 PRIMARY KEY ("LAND_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
--------------------------------------------------------
--  DDL for Table SHOP_LOG
--------------------------------------------------------

  CREATE TABLE "HR"."SHOP_LOG" 
   (	"LOG_ID" NUMBER, 
	"USER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"ITEM_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(10) NOT NULL ENABLE, 
	"QUANTITY" NUMBER NOT NULL ENABLE, 
	"GOLD" NUMBER NOT NULL ENABLE, 
	"LOG_DATE" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 FOREIGN KEY ("USER_ID")
	  REFERENCES "HR"."USERS" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
--------------------------------------------------------
--  DDL for Table ITEM
--------------------------------------------------------

  CREATE TABLE "HR"."ITEM" 
   (	"ITEM_ID" NUMBER(10,0), 
	"ITEM_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"PRICE" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(100), 
	"EFFECT_TYPE" VARCHAR2(20), 
	"EFFECT_VALUE" NUMBER(10,0), 
	 PRIMARY KEY ("ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
--------------------------------------------------------
--  DDL for Table INVENTORY
--------------------------------------------------------

  CREATE TABLE "HR"."INVENTORY" 
   (	"ITEM_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"QUANTITY" NUMBER(10,0) DEFAULT 0, 
	 CONSTRAINT "INVENTORY_QTY_CK" CHECK (QUANTITY >= 0) ENABLE, 
	 CONSTRAINT "INVENTORY_PK" PRIMARY KEY ("USER_ID", "ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_USER_ID" FOREIGN KEY ("USER_ID")
	  REFERENCES "HR"."USERS" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
--------------------------------------------------------
--  DDL for Table GAME_LOG
--------------------------------------------------------

  CREATE TABLE "HR"."GAME_LOG" 
   (	"GAME_ID" NUMBER, 
	"USER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(10) NOT NULL ENABLE, 
	"TURN_COUNT" NUMBER, 
	"PLAY_DATE" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("GAME_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 FOREIGN KEY ("USER_ID")
	  REFERENCES "HR"."USERS" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
--------------------------------------------------------
--  DDL for Table CARD
--------------------------------------------------------

  CREATE TABLE "HR"."CARD" 
   (	"CARD_ID" NUMBER(10,0), 
	"CARD_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(100) NOT NULL ENABLE, 
	"EFFECT_TYPE" VARCHAR2(30) NOT NULL ENABLE, 
	"EFFECT_VALUE" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	 PRIMARY KEY ("CARD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
--------------------------------------------------------
--  DDL for View EMP_DETAILS_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "HR"."EMP_DETAILS_VIEW" ("EMPLOYEE_ID", "JOB_ID", "MANAGER_ID", "DEPARTMENT_ID", "LOCATION_ID", "COUNTRY_ID", "FIRST_NAME", "LAST_NAME", "SALARY", "COMMISSION_PCT", "DEPARTMENT_NAME", "JOB_TITLE", "CITY", "STATE_PROVINCE", "COUNTRY_NAME", "REGION_NAME") AS 
  SELECT
  e.employee_id,
  e.job_id,
  e.manager_id,
  e.department_id,
  d.location_id,
  l.country_id,
  e.first_name,
  e.last_name,
  e.salary,
  e.commission_pct,
  d.department_name,
  j.job_title,
  l.city,
  l.state_province,
  c.country_name,
  r.region_name
FROM
  employees e,
  departments d,
  jobs j,
  locations l,
  countries c,
  regions r
WHERE e.department_id = d.department_id
  AND d.location_id = l.location_id
  AND l.country_id = c.country_id
  AND c.region_id = r.region_id
  AND j.job_id = e.job_id
WITH READ ONLY
REM INSERTING into HR.CARD
SET DEFINE OFF;
Insert into HR.CARD (CARD_ID,CARD_NAME,DESCRIPTION,EFFECT_TYPE,EFFECT_VALUE) values (1,'보너스 지급','골드 500 획득','ADD_GOLD',500);
Insert into HR.CARD (CARD_ID,CARD_NAME,DESCRIPTION,EFFECT_TYPE,EFFECT_VALUE) values (2,'세금 납부','골드 300 차감','LOSE_GOLD',300);
Insert into HR.CARD (CARD_ID,CARD_NAME,DESCRIPTION,EFFECT_TYPE,EFFECT_VALUE) values (3,'출발지 이동','출발지로 이동','MOVE_TO_START',0);
Insert into HR.CARD (CARD_ID,CARD_NAME,DESCRIPTION,EFFECT_TYPE,EFFECT_VALUE) values (4,'감옥행','감옥으로 이동','MOVE_TO_JAIL',0);
Insert into HR.CARD (CARD_ID,CARD_NAME,DESCRIPTION,EFFECT_TYPE,EFFECT_VALUE) values (5,'통행료 면제','다음 통행료 면제','TOLL_FREE',1);
Insert into HR.CARD (CARD_ID,CARD_NAME,DESCRIPTION,EFFECT_TYPE,EFFECT_VALUE) values (6,'관광지 특수 개발','관광지 통행료 2배','ATTRACTION_TOLL_X2',2);
Insert into HR.CARD (CARD_ID,CARD_NAME,DESCRIPTION,EFFECT_TYPE,EFFECT_VALUE) values (7,'정부 규제','상대 통행료 절반','ENEMY_TOLL_HALF',50);
Insert into HR.CARD (CARD_ID,CARD_NAME,DESCRIPTION,EFFECT_TYPE,EFFECT_VALUE) values (8,'기차 특급권','기차여행 무료 사용','FREE_TRAIN',1);
Insert into HR.CARD (CARD_ID,CARD_NAME,DESCRIPTION,EFFECT_TYPE,EFFECT_VALUE) values (9,'행운의 주사위','다음 주사위 +3','DICE_BONUS',3);
Insert into HR.CARD (CARD_ID,CARD_NAME,DESCRIPTION,EFFECT_TYPE,EFFECT_VALUE) values (10,'즉시 이동','원하는 칸으로 이동','FREE_MOVE',1);
REM INSERTING into HR.GAME_LOG
SET DEFINE OFF;
REM INSERTING into HR.INVENTORY
SET DEFINE OFF;
REM INSERTING into HR.ITEM
SET DEFINE OFF;
Insert into HR.ITEM (ITEM_ID,ITEM_NAME,PRICE,DESCRIPTION,EFFECT_TYPE,EFFECT_VALUE) values (1,'고속주사위',300,'주사위 결과 +3','PLUS',3);
Insert into HR.ITEM (ITEM_ID,ITEM_NAME,PRICE,DESCRIPTION,EFFECT_TYPE,EFFECT_VALUE) values (2,'저속주사위',300,'주사위 결과 -3','MINUS',3);
Insert into HR.ITEM (ITEM_ID,ITEM_NAME,PRICE,DESCRIPTION,EFFECT_TYPE,EFFECT_VALUE) values (3,'더블주사위',500,'다음 턴 더블','DOUBLE',1);
REM INSERTING into HR.LAND
SET DEFINE OFF;
Insert into HR.LAND (LAND_ID,LAND_TYPE,LAND_NAME,BUY_PRICE,TOLL_PRICE,UPGRADE_COST,UPGRADE_MAX) values (0,'START','START',0,0,0,0);
Insert into HR.LAND (LAND_ID,LAND_TYPE,LAND_NAME,BUY_PRICE,TOLL_PRICE,UPGRADE_COST,UPGRADE_MAX) values (1,'NORMAL','강릉',700,70,200,3);
Insert into HR.LAND (LAND_ID,LAND_TYPE,LAND_NAME,BUY_PRICE,TOLL_PRICE,UPGRADE_COST,UPGRADE_MAX) values (2,'NORMAL','춘천',600,60,200,3);
Insert into HR.LAND (LAND_ID,LAND_TYPE,LAND_NAME,BUY_PRICE,TOLL_PRICE,UPGRADE_COST,UPGRADE_MAX) values (3,'ATTRACTION','북한산',1000,120,0,0);
Insert into HR.LAND (LAND_ID,LAND_TYPE,LAND_NAME,BUY_PRICE,TOLL_PRICE,UPGRADE_COST,UPGRADE_MAX) values (4,'NORMAL','경주',700,70,250,3);
Insert into HR.LAND (LAND_ID,LAND_TYPE,LAND_NAME,BUY_PRICE,TOLL_PRICE,UPGRADE_COST,UPGRADE_MAX) values (5,'NORMAL','안동',700,70,250,3);
Insert into HR.LAND (LAND_ID,LAND_TYPE,LAND_NAME,BUY_PRICE,TOLL_PRICE,UPGRADE_COST,UPGRADE_MAX) values (6,'NORMAL','천안',800,80,300,3);
Insert into HR.LAND (LAND_ID,LAND_TYPE,LAND_NAME,BUY_PRICE,TOLL_PRICE,UPGRADE_COST,UPGRADE_MAX) values (7,'JAIL','감옥',0,0,0,0);
Insert into HR.LAND (LAND_ID,LAND_TYPE,LAND_NAME,BUY_PRICE,TOLL_PRICE,UPGRADE_COST,UPGRADE_MAX) values (8,'NORMAL','여수',900,90,300,3);
Insert into HR.LAND (LAND_ID,LAND_TYPE,LAND_NAME,BUY_PRICE,TOLL_PRICE,UPGRADE_COST,UPGRADE_MAX) values (9,'NORMAL','여주',900,90,300,3);
Insert into HR.LAND (LAND_ID,LAND_TYPE,LAND_NAME,BUY_PRICE,TOLL_PRICE,UPGRADE_COST,UPGRADE_MAX) values (10,'ATTRACTION','독도',1500,200,0,0);
Insert into HR.LAND (LAND_ID,LAND_TYPE,LAND_NAME,BUY_PRICE,TOLL_PRICE,UPGRADE_COST,UPGRADE_MAX) values (11,'NORMAL','제주도',1200,120,400,3);
Insert into HR.LAND (LAND_ID,LAND_TYPE,LAND_NAME,BUY_PRICE,TOLL_PRICE,UPGRADE_COST,UPGRADE_MAX) values (12,'CARD','카드1',0,0,0,0);
Insert into HR.LAND (LAND_ID,LAND_TYPE,LAND_NAME,BUY_PRICE,TOLL_PRICE,UPGRADE_COST,UPGRADE_MAX) values (13,'NORMAL','포항',1000,100,350,3);
Insert into HR.LAND (LAND_ID,LAND_TYPE,LAND_NAME,BUY_PRICE,TOLL_PRICE,UPGRADE_COST,UPGRADE_MAX) values (14,'EXPO','엑스포',0,0,0,0);
Insert into HR.LAND (LAND_ID,LAND_TYPE,LAND_NAME,BUY_PRICE,TOLL_PRICE,UPGRADE_COST,UPGRADE_MAX) values (15,'NORMAL','인천',1100,110,400,3);
Insert into HR.LAND (LAND_ID,LAND_TYPE,LAND_NAME,BUY_PRICE,TOLL_PRICE,UPGRADE_COST,UPGRADE_MAX) values (16,'NORMAL','대구',1200,120,400,3);
Insert into HR.LAND (LAND_ID,LAND_TYPE,LAND_NAME,BUY_PRICE,TOLL_PRICE,UPGRADE_COST,UPGRADE_MAX) values (17,'NORMAL','대전',1300,130,450,3);
Insert into HR.LAND (LAND_ID,LAND_TYPE,LAND_NAME,BUY_PRICE,TOLL_PRICE,UPGRADE_COST,UPGRADE_MAX) values (18,'ATTRACTION','어린이대공원',1600,220,0,0);
Insert into HR.LAND (LAND_ID,LAND_TYPE,LAND_NAME,BUY_PRICE,TOLL_PRICE,UPGRADE_COST,UPGRADE_MAX) values (19,'ATTRACTION','남산',1700,240,0,0);
Insert into HR.LAND (LAND_ID,LAND_TYPE,LAND_NAME,BUY_PRICE,TOLL_PRICE,UPGRADE_COST,UPGRADE_MAX) values (20,'NORMAL','울산',1400,140,450,3);
Insert into HR.LAND (LAND_ID,LAND_TYPE,LAND_NAME,BUY_PRICE,TOLL_PRICE,UPGRADE_COST,UPGRADE_MAX) values (21,'TRAIN','기차여행',0,0,0,0);
Insert into HR.LAND (LAND_ID,LAND_TYPE,LAND_NAME,BUY_PRICE,TOLL_PRICE,UPGRADE_COST,UPGRADE_MAX) values (22,'NORMAL','전주',1000,100,350,3);
Insert into HR.LAND (LAND_ID,LAND_TYPE,LAND_NAME,BUY_PRICE,TOLL_PRICE,UPGRADE_COST,UPGRADE_MAX) values (23,'NORMAL','광주',1100,110,400,3);
Insert into HR.LAND (LAND_ID,LAND_TYPE,LAND_NAME,BUY_PRICE,TOLL_PRICE,UPGRADE_COST,UPGRADE_MAX) values (24,'CARD','카드2',0,0,0,0);
Insert into HR.LAND (LAND_ID,LAND_TYPE,LAND_NAME,BUY_PRICE,TOLL_PRICE,UPGRADE_COST,UPGRADE_MAX) values (25,'NORMAL','부산',1800,250,700,3);
Insert into HR.LAND (LAND_ID,LAND_TYPE,LAND_NAME,BUY_PRICE,TOLL_PRICE,UPGRADE_COST,UPGRADE_MAX) values (26,'LUCKY','복불복',0,0,0,0);
Insert into HR.LAND (LAND_ID,LAND_TYPE,LAND_NAME,BUY_PRICE,TOLL_PRICE,UPGRADE_COST,UPGRADE_MAX) values (27,'NORMAL','서울',2000,300,800,3);
REM INSERTING into HR.LOGIN_LOG
SET DEFINE OFF;
REM INSERTING into HR.SHOP_LOG
SET DEFINE OFF;
REM INSERTING into HR.USERS
SET DEFINE OFF;
Insert into HR.USERS (USER_ID,PASSWORD,USER_NAME,QUESTION,ANSWER,GOLD,EXPERIENCE) values ('shinhan','0514','shin','좋아하는동물','강아지',0,0);
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."USERS_PK" ON "HR"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
--------------------------------------------------------
--  DDL for Index SYS_C007032
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007032" ON "HR"."LOGIN_LOG" ("LOG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
--------------------------------------------------------
--  DDL for Index SYS_C007051
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007051" ON "HR"."LAND" ("LAND_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
--------------------------------------------------------
--  DDL for Index SYS_C007039
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007039" ON "HR"."SHOP_LOG" ("LOG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
--------------------------------------------------------
--  DDL for Index SYS_C007059
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007059" ON "HR"."ITEM" ("ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
--------------------------------------------------------
--  DDL for Index INVENTORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."INVENTORY_PK" ON "HR"."INVENTORY" ("USER_ID", "ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
--------------------------------------------------------
--  DDL for Index SYS_C007044
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007044" ON "HR"."GAME_LOG" ("GAME_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
--------------------------------------------------------
--  DDL for Index SYS_C007056
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007056" ON "HR"."CARD" ("CARD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
--------------------------------------------------------
--  DDL for Procedure ADD_JOB_HISTORY
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "HR"."ADD_JOB_HISTORY" 
  (  p_emp_id          job_history.employee_id%type
   , p_start_date      job_history.start_date%type
   , p_end_date        job_history.end_date%type
   , p_job_id          job_history.job_id%type
   , p_department_id   job_history.department_id%type
   )
IS
BEGIN
  INSERT INTO job_history (employee_id, start_date, end_date,
                           job_id, department_id)
    VALUES(p_emp_id, p_start_date, p_end_date, p_job_id, p_department_id);
END add_job_history;
--------------------------------------------------------
--  DDL for Procedure SECURE_DML
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "HR"."SECURE_DML" 
IS
BEGIN
  IF TO_CHAR (SYSDATE, 'HH24:MI') NOT BETWEEN '08:00' AND '18:00'
        OR TO_CHAR (SYSDATE, 'DY') IN ('SAT', 'SUN') THEN
	RAISE_APPLICATION_ERROR (-20205,
		'You may only make changes during normal office hours');
  END IF;
END secure_dml;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "HR"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
  ALTER TABLE "HR"."USERS" MODIFY ("EXPERIENCE" NOT NULL ENABLE)
  ALTER TABLE "HR"."USERS" MODIFY ("GOLD" NOT NULL ENABLE)
  ALTER TABLE "HR"."USERS" MODIFY ("ANSWER" NOT NULL ENABLE)
  ALTER TABLE "HR"."USERS" MODIFY ("QUESTION" NOT NULL ENABLE)
  ALTER TABLE "HR"."USERS" MODIFY ("USER_NAME" NOT NULL ENABLE)
  ALTER TABLE "HR"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE)
  ALTER TABLE "HR"."USERS" MODIFY ("USER_ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table LOGIN_LOG
--------------------------------------------------------

  ALTER TABLE "HR"."LOGIN_LOG" ADD PRIMARY KEY ("LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
  ALTER TABLE "HR"."LOGIN_LOG" MODIFY ("DESCRIPTION" NOT NULL ENABLE)
  ALTER TABLE "HR"."LOGIN_LOG" MODIFY ("USER_ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table LAND
--------------------------------------------------------

  ALTER TABLE "HR"."LAND" ADD PRIMARY KEY ("LAND_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
  ALTER TABLE "HR"."LAND" MODIFY ("UPGRADE_MAX" NOT NULL ENABLE)
  ALTER TABLE "HR"."LAND" MODIFY ("UPGRADE_COST" NOT NULL ENABLE)
  ALTER TABLE "HR"."LAND" MODIFY ("TOLL_PRICE" NOT NULL ENABLE)
  ALTER TABLE "HR"."LAND" MODIFY ("BUY_PRICE" NOT NULL ENABLE)
  ALTER TABLE "HR"."LAND" MODIFY ("LAND_NAME" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table SHOP_LOG
--------------------------------------------------------

  ALTER TABLE "HR"."SHOP_LOG" ADD PRIMARY KEY ("LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
  ALTER TABLE "HR"."SHOP_LOG" MODIFY ("GOLD" NOT NULL ENABLE)
  ALTER TABLE "HR"."SHOP_LOG" MODIFY ("QUANTITY" NOT NULL ENABLE)
  ALTER TABLE "HR"."SHOP_LOG" MODIFY ("DESCRIPTION" NOT NULL ENABLE)
  ALTER TABLE "HR"."SHOP_LOG" MODIFY ("ITEM_ID" NOT NULL ENABLE)
  ALTER TABLE "HR"."SHOP_LOG" MODIFY ("USER_ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table ITEM
--------------------------------------------------------

  ALTER TABLE "HR"."ITEM" ADD PRIMARY KEY ("ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
  ALTER TABLE "HR"."ITEM" MODIFY ("PRICE" NOT NULL ENABLE)
  ALTER TABLE "HR"."ITEM" MODIFY ("ITEM_NAME" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table INVENTORY
--------------------------------------------------------

  ALTER TABLE "HR"."INVENTORY" ADD CONSTRAINT "INVENTORY_PK" PRIMARY KEY ("USER_ID", "ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
  ALTER TABLE "HR"."INVENTORY" ADD CONSTRAINT "INVENTORY_QTY_CK" CHECK (QUANTITY >= 0) ENABLE
  ALTER TABLE "HR"."INVENTORY" MODIFY ("USER_ID" NOT NULL ENABLE)
  ALTER TABLE "HR"."INVENTORY" MODIFY ("ITEM_ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table GAME_LOG
--------------------------------------------------------

  ALTER TABLE "HR"."GAME_LOG" ADD PRIMARY KEY ("GAME_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
  ALTER TABLE "HR"."GAME_LOG" MODIFY ("DESCRIPTION" NOT NULL ENABLE)
  ALTER TABLE "HR"."GAME_LOG" MODIFY ("USER_ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table CARD
--------------------------------------------------------

  ALTER TABLE "HR"."CARD" ADD PRIMARY KEY ("CARD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
  ALTER TABLE "HR"."CARD" MODIFY ("EFFECT_VALUE" NOT NULL ENABLE)
  ALTER TABLE "HR"."CARD" MODIFY ("EFFECT_TYPE" NOT NULL ENABLE)
  ALTER TABLE "HR"."CARD" MODIFY ("DESCRIPTION" NOT NULL ENABLE)
  ALTER TABLE "HR"."CARD" MODIFY ("CARD_NAME" NOT NULL ENABLE)
--------------------------------------------------------
--  Ref Constraints for Table LOGIN_LOG
--------------------------------------------------------

  ALTER TABLE "HR"."LOGIN_LOG" ADD CONSTRAINT "LOGIN_LOG_USER_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "HR"."USERS" ("USER_ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table SHOP_LOG
--------------------------------------------------------

  ALTER TABLE "HR"."SHOP_LOG" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "HR"."USERS" ("USER_ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table INVENTORY
--------------------------------------------------------

  ALTER TABLE "HR"."INVENTORY" ADD CONSTRAINT "FK_USER_ID" FOREIGN KEY ("USER_ID")
	  REFERENCES "HR"."USERS" ("USER_ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table GAME_LOG
--------------------------------------------------------

  ALTER TABLE "HR"."GAME_LOG" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "HR"."USERS" ("USER_ID") ENABLE
